### ISSUE TITLE
Kinect Azure Body Masking

### ISSUE THREAD

**Issue by Verlinch** [eshirima/Test#1]

**Comment by eshirima** [comment]
Are you referring to [this](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1082)? If yes, here's the [answer](https://stackoverflow.com/questions/60196877/azure-kinect-crop-out-body-using-body-index-map). Don't forget to upvote, thanks!

**Comment by Verlinch** [comment]
Yes thank you! Would it be possible for you to share the code for that part? I am confused on how your body mask extraction comes together with the code from the samples
